version: '2'
services:
    buyittogether-app:
        image: buyittogether
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://buyittogether-postgresql:5432/postgres
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    buyittogether-postgresql:
        extends:
            file: postgresql.yml
            service: buyittogether-postgresql
